"""SMTP Email Helper — sends project insight reports via Gmail (TLS).

Used as a fallback when the n8n webhook is unavailable or fails.
Uses Python's built-in smtplib — no external dependencies required.
"""

import os
import ssl
import logging
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

logger = logging.getLogger(__name__)

SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587


def _build_email_body(payload: dict) -> str:
    """Convert the report payload into a clean plain-text email body."""
    lines: list[str] = []

    # Summary section (already human-readable)
    summary = payload.get("summary", "")
    if summary:
        lines.append(summary)
        lines.append("")

    # Stats table
    stats = payload.get("stats", {})
    if stats:
        lines.append("── Key Metrics ──")
        lines.append(f"  Total Commits:      {stats.get('total_commits', 0)}")
        lines.append(f"  Active Developers:  {stats.get('active_developers', 0)}")
        lines.append(f"  Modules Tracked:    {stats.get('modules_tracked', 0)}")
        if stats.get("tasks_total", 0) > 0:
            lines.append(
                f"  Requirements:       {stats['tasks_completed']} done, "
                f"{stats['tasks_partial']} partial, "
                f"{stats['tasks_not_started']} not started "
                f"(of {stats['tasks_total']})"
            )
        lines.append("")

    # Risk modules
    risks = payload.get("risks", [])
    if risks:
        lines.append("── High-Risk Modules ──")
        for r in risks:
            lines.append(
                f"  ⚠ {r.get('module', '?')} — "
                f"owned {r.get('ownership_pct', 0)}% by {r.get('owner', '?')}"
            )
        lines.append("")

    # Developers
    devs = payload.get("developers", [])
    if devs:
        lines.append("── Top Contributors ──")
        for d in devs:
            lines.append(
                f"  • {d.get('name', '?')} — "
                f"{d.get('commits', 0)} commits, "
                f"impact {d.get('impact_score', 0)}, "
                f"risk {d.get('risk_label', 'Low')}"
            )
        lines.append("")

    # Recommendations
    recs = payload.get("recommendations", [])
    if recs:
        lines.append("── Recommendations ──")
        for i, r in enumerate(recs, 1):
            lines.append(f"  {i}. [{r.get('priority', 'Low')}] {r.get('title', '')}")
            if r.get("text"):
                lines.append(f"     {r['text']}")
        lines.append("")

    lines.append("—")
    lines.append("Generated by CodePulse · AI Developer Intelligence Platform")

    return "\n".join(lines)


def send_smtp_email(payload: dict) -> bool:
    """
    Send an email via Gmail SMTP with TLS.

    Reads EMAIL_SENDER and EMAIL_APP_PASSWORD from environment variables.
    Returns True on success, False on failure — NEVER raises.
    """
    sender = os.getenv("EMAIL_SENDER", "").strip()
    app_password = os.getenv("EMAIL_APP_PASSWORD", "").strip()

    if not sender or not app_password:
        logger.warning(
            "SMTP fallback skipped — EMAIL_SENDER or EMAIL_APP_PASSWORD not set."
        )
        return False

    recipient = payload.get("email", "").strip()
    if not recipient:
        logger.warning("SMTP fallback skipped — no recipient email in payload.")
        return False

    subject = payload.get("subject", "CodePulse Project Report")
    body = _build_email_body(payload)

    try:
        msg = MIMEMultipart("alternative")
        msg["From"] = sender
        msg["To"] = recipient
        msg["Subject"] = subject
        msg.attach(MIMEText(body, "plain", "utf-8"))

        context = ssl.create_default_context()
        with smtplib.SMTP(SMTP_SERVER, SMTP_PORT, timeout=15) as server:
            server.ehlo()
            server.starttls(context=context)
            server.ehlo()
            server.login(sender, app_password)
            server.sendmail(sender, [recipient], msg.as_string())

        logger.info("SMTP email sent successfully to %s", recipient)
        return True

    except smtplib.SMTPAuthenticationError:
        logger.warning(
            "SMTP authentication failed — check EMAIL_SENDER and EMAIL_APP_PASSWORD."
        )
        return False
    except Exception as e:
        logger.warning("SMTP email failed: %s", str(e))
        return False
